version: "3.5"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - gitarista-db:/var/lib/postgresql/data
    #expose:
    #  - "5432"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: pg_isready -U ${DB_USER}
      interval: 2s
      timeout: 3s
      retries: 40
    logging:
      options:
        max-size: "100m"
        max-file: "3"

volumes:
  gitarista-db:
    name: gitarista-db
    external: true
