FROM python:3.11-bullseye
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /gitarista
RUN apt-get update && apt-get upgrade -y
COPY ./django ./
COPY ./.env ./
RUN pip install -r /django/requirements.txt
RUN pip install gunicorn
COPY ./entrypoint.server.sh ./
RUN chmod +x entrypoint.server.sh
ENTRYPOINT ["bash", "entrypoint.server.sh"]
