# Generated by Django 4.2.1 on 2023-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.BigAutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=40, unique=True)),
                ("password", models.CharField(max_length=40)),
                (
                    "public_info",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
