# Generated by Django 4.2.1 on 2023-06-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accord",
            fields=[
                (
                    "accord_id",
                    models.BigAutoField(
                        db_column="accord_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                (
                    "link",
                    models.URLField(blank=True, default="", max_length=400, null=True),
                ),
                ("short_name", models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "author_id",
                    models.BigAutoField(
                        db_column="author_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "link",
                    models.URLField(blank=True, default="", max_length=400, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "genre_id",
                    models.BigAutoField(
                        db_column="genre_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "song_id",
                    models.BigAutoField(
                        db_column="song_id", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "link",
                    models.URLField(blank=True, default="", max_length=400, null=True),
                ),
                (
                    "text_with_accords",
                    models.TextField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "author_id",
                    models.ForeignKey(
                        db_column="author_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="song.author",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "song_id",
                    models.ForeignKey(
                        db_column="song_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="song.song",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("song_id", "user_id")},
            },
        ),
        migrations.CreateModel(
            name="SongGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre_id",
                    models.ForeignKey(
                        db_column="genre_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="song.genre",
                    ),
                ),
                (
                    "song_id",
                    models.ForeignKey(
                        db_column="song_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="song.song",
                    ),
                ),
            ],
            options={
                "unique_together": {("song_id", "genre_id")},
            },
        ),
    ]
