# Generated by Django 4.2.1 on 2023-06-16 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("song", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="songlike",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="songgenre",
            name="genre_id",
            field=models.ForeignKey(
                db_column="genre_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="song.genre",
            ),
        ),
        migrations.AddField(
            model_name="songgenre",
            name="song_id",
            field=models.ForeignKey(
                db_column="song_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="song.song",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="author_id",
            field=models.ForeignKey(
                db_column="author_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="song.author",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="songlike",
            unique_together={("song_id", "user_id")},
        ),
        migrations.AlterUniqueTogether(
            name="songgenre",
            unique_together={("song_id", "genre_id")},
        ),
    ]
