# Generated by Django 4.2.1 on 2023-05-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("song", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                (
                    "link",
                    models.URLField(blank=True, default="", max_length=400, null=True),
                ),
                ("short_name", models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "link",
                    models.URLField(blank=True, default="", max_length=400, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "link",
                    models.URLField(blank=True, default="", max_length=400, null=True),
                ),
                (
                    "text_with_accords",
                    models.TextField(
                        blank=True, default="", max_length=10000, null=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="song.author"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="song.song"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="song.genre"
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="song.song"
                    ),
                ),
            ],
        ),
    ]
