# Generated by Django 4.2.1 on 2023-06-18 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("song", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="songs",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="songlikes",
            name="song_id",
            field=models.ForeignKey(
                db_column="song_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="song.songs",
            ),
        ),
        migrations.AddField(
            model_name="songlikes",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="songgenres",
            name="genre_id",
            field=models.ForeignKey(
                db_column="genre_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="song.genres",
            ),
        ),
        migrations.AddField(
            model_name="songgenres",
            name="song_id",
            field=models.ForeignKey(
                db_column="song_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="song.songs",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="songlikes",
            unique_together={("song_id", "user_id")},
        ),
        migrations.AlterUniqueTogether(
            name="songgenres",
            unique_together={("song_id", "genre_id")},
        ),
    ]
