# Generated by Django 4.2.1 on 2023-06-20 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("song", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accords",
            options={"verbose_name_plural": "Accords"},
        ),
        migrations.AlterModelOptions(
            name="authors",
            options={"verbose_name_plural": "Authors"},
        ),
        migrations.AlterModelOptions(
            name="genres",
            options={"verbose_name_plural": "Genres"},
        ),
        migrations.AlterModelOptions(
            name="songgenres",
            options={"verbose_name_plural": "Song genres"},
        ),
        migrations.AlterModelOptions(
            name="songlikes",
            options={"verbose_name_plural": "Song likes"},
        ),
        migrations.AlterModelOptions(
            name="songs",
            options={"verbose_name_plural": "Songs"},
        ),
    ]
