# Generated by Django 4.2.1 on 2023-06-02 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("song", "0002_accord_author_song_songlike_songgenre"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="songgenre",
            unique_together={("song", "genre")},
        ),
    ]
