# Generated by Django 4.2.1 on 2023-06-02 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
        ("song", "0003_alter_songgenre_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="songlike",
            unique_together={("song", "user")},
        ),
    ]
